spring:
  datasource:
    druid:
      url: "jdbc:mysql://8.134.65.90/customer_relationship_management?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false"
      username: "root"
      password: "root"
      # 最大连接数
      max-active: 8
