spring:
  #配置数据库连接驱动
  datasource:
    type: "com.alibaba.druid.pool.DruidDataSource"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    #配置连接地址
    druid:
      url: "jdbc:mysql://8.134.65.90:3306/customer_relationship_management?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false"
      username: "root"
      password: "root"
      max-active: 8
    #配置SQL图形化界面
      #开启过滤防火墙
      filter: "start,wall,slf4j"
      web-stat-filter:
        #开启监控信息
        enabled: true
        #拦截所有请求
        url-pattern: "/*"
        #排除不监控资源
        exclusions: "*.js,*.jpg,*.css,/druid/*"
      #配置拦截web显示界面
      stat-view-servlet:
        enabled: true
        #访问监控的url路径
        url-pattern: "/druid/*"
        #配置账号密码
        login-username: "admin"
        login-password: "admin"
        #mybatis配置
#mybatis:
#  mapper-locations: "classpath:mapper/**/*.xml"
#  # 配置entity的别名
#  type-aliases-package: "com.qf.business.**.entity"
#  configuration:
#    map-underscore-to-camel-case: true

#配置mybatis-plus
mybatis-plus:
  #注册本地所有的mapper.xml资源文件
  mapper-locations: "classpath:mapper/**/*.xml"
  #配置entity别名
  type-aliases-package: "com.qf.business.entity"
  #开启别名大小转转换
  configuration:
    map-underscore-to-camel-case: true
#debug日志配置mapper测试日志
logging:
  level:
    com.qf.business.mapper: debug
page helper:
  reasonable: true
